// Web Worker for text processing
// This worker handles text segmentation and lemmatization asynchronously

// Type definitions (same as useBookshelf.ts)
interface ProcessedSegment {
  text: string;
  lemma: string;
  type: "word" | "space" | "punctuation";
}

interface ProcessedParagraph {
  segments: ProcessedSegment[];
  headingLevel?: number;
}

type ProcessedContent = ProcessedParagraph[];

// Lemmatization data structures
const irregularVerbs: Record<string, string> = {
  "arose": "arise",
  "awoke": "awake",
  "was": "be",
  "were": "be",
  "beat": "beat",
  "became": "become",
  "began": "begin",
  "begun": "begin",
  "bent": "bend",
  "bet": "bet",
  "bid": "bid",
  "bound": "bind",
  "bit": "bite",
  "bitten": "bite",
  "bled": "bleed",
  "blew": "blow",
  "blown": "blow",
  "broke": "break",
  "broken": "break",
  "bred": "breed",
  "brought": "bring",
  "broadcast": "broadcast",
  "built": "build",
  "burned": "burn",
  "burnt": "burn",
  "burst": "burst",
  "bought": "buy",
  "caught": "catch",
  "chose": "choose",
  "chosen": "choose",
  "clung": "cling",
  "came": "come",
  "cost": "cost",
  "crept": "creep",
  "cut": "cut",
  "dealt": "deal",
  "dug": "dig",
  "dived": "dive",
  "done": "do",
  "drew": "draw",
  "drawn": "draw",
  "drank": "drink",
  "drunk": "drink",
  "drove": "drive",
  "driven": "drive",
  "dwelt": "dwell",
  "ate": "eat",
  "eaten": "eat",
  "fallen": "fall",
  "fell": "fall",
  "fed": "feed",
  "felt": "feel",
  "fought": "fight",
  "found": "find",
  "fit": "fit",
  "fled": "flee",
  "flew": "fly",
  "flown": "fly",
  "forbade": "forbid",
  "forecast": "forecast",
  "forgave": "forgive",
  "forgiven": "forgive",
  "forgot": "forget",
  "forgotten": "forget",
  "forsook": "forsake",
  "forsaken": "forsake",
  "froze": "freeze",
  "frozen": "freeze",
  "gave": "give",
  "given": "give",
  "went": "go",
  "gone": "go",
  "ground": "grind",
  "grew": "grow",
  "grown": "grow",
  "hung": "hang",
  "had": "have",
  "heard": "hear",
  "hid": "hide",
  "hidden": "hide",
  "hit": "hit",
  "hurt": "hurt",
  "kept": "keep",
  "knelt": "kneel",
  "knit": "knit",
  "knew": "know",
  "known": "know",
  "laid": "lay",
  "led": "lead",
  "left": "leave",
  "lent": "lend",
  "let": "let",
  "lay": "lie",
  "lain": "lie",
  "lit": "light",
  "lost": "lose",
  "made": "make",
  "meant": "mean",
  "met": "meet",
  "mistook": "mistake",
  "mistaken": "mistake",
  "mowed": "mow",
  "overcame": "overcome",
  "overdid": "overdo",
  "overdone": "overdo",
  "overtook": "overtake",
  "overtaken": "overtake",
  "paid": "pay",
  "pled": "plead",
  "proved": "prove",
  "put": "put",
  "quit": "quit",
  "read": "read",
  "rid": "rid",
  "rode": "ride",
  "ridden": "ride",
  "rang": "ring",
  "rung": "ring",
  "rose": "rise",
  "risen": "rise",
  "ran": "run",
  "sawed": "saw",
  "said": "say",
  "saw": "see",
  "seen": "see",
  "sought": "seek",
  "sold": "sell",
  "sent": "send",
  "sewed": "sew",
  "shook": "shake",
  "shaken": "shake",
  "shone": "shine",
  "shot": "shot",
  "showed": "show",
  "shown": "show",
  "shrank": "shrink",
  "shrunk": "shrink",
  "sung": "sing",
  "sank": "sink",
  "sunk": "sink",
  "sat": "sit",
  "slept": "sleep",
  "slid": "slide",
  "smelt": "smell",
  "sowed": "sow",
  "spoke": "speak",
  "spoken": "speak",
  "sped": "speed",
  "spun": "spin",
  "spat": "spit",
  "split": "split",
  "spoilt": "spoil",
  "spread": "spread",
  "stood": "stand",
  "stole": "steal",
  "stolen": "steal",
  "stuck": "stick",
  "stung": "sting",
  "stank": "stink",
  "stunk": "stink",
  "strove": "strive",
  "striven": "strive",
  "swore": "swear",
  "sworn": "swear",
  "swept": "sweep",
  "swollen": "swell",
  "took": "take",
  "taken": "take",
  "taught": "teach",
  "tore": "tear",
  "torn": "tear",
  "told": "tell",
  "thought": "think",
  "threw": "throw",
  "thrown": "throw",
  "thrust": "thrust",
  "underwent": "undergo",
  "undergone": "undergo",
  "understood": "understand",
  "woke": "wake",
  "woken": "wake",
  "wore": "wear",
  "worn": "wear",
  "wove": "weave",
  "won": "win",
  "wound": "wind",
  "withheld": "withhold",
  "withdrawn": "withdraw",
  "withstood": "withstand",
  "wrung": "wring",
  "written": "write",
  "wrote": "write",
};

// Irregular nouns
const irregularNouns: Record<string, string> = {
  "children": "child",
  "feet": "foot",
  "teeth": "tooth",
  "geese": "goose",
  "mice": "mouse",
  "men": "man",
  "women": "woman",
  "oxen": "ox",
  "sheep": "sheep",
  "deer": "deer",
  "fish": "fish",
  "fruit": "fruit",
  "species": "species",
  "aircraft": "aircraft",
  "data": "data",
  "means": "means",
  "offspring": "offspring",
  "progress": "progress",
  "salmon": "salmon",
  "staff": "staff",
  "trout": "trout",
};

// Suffix rules
const suffixRules: Array<{ suffix: string; remove: number; add?: string }> = [
  { suffix: "ies", remove: 3, add: "y" },
  { suffix: "es", remove: 2 },
  { suffix: "s", remove: 1 },
  { suffix: "ing", remove: 3 },
  { suffix: "ed", remove: 2 },
  { suffix: "er", remove: 2 },
  { suffix: "est", remove: 3 },
  { suffix: "ly", remove: 2 },
  { suffix: "tion", remove: 4 },
  { suffix: "sion", remove: 4 },
  { suffix: "ment", remove: 4 },
  { suffix: "ness", remove: 4 },
  { suffix: "able", remove: 4 },
  { suffix: "ible", remove: 4 },
  { suffix: "al", remove: 2 },
  { suffix: "ful", remove: 3 },
  { suffix: "less", remove: 4 },
  { suffix: "ous", remove: 3 },
  { suffix: "ive", remove: 3 },
];

// Common verb forms mapping
const verbForms: Record<string, string> = {
  "running": "run",
  "runs": "run",
  "ran": "run",
  "walking": "walk",
  "walks": "walk",
  "walked": "walk",
  "taking": "take",
  "takes": "take",
  "took": "take",
  "taken": "take",
  "giving": "give",
  "gives": "give",
  "gave": "give",
  "given": "give",
  "making": "make",
  "makes": "make",
  "made": "make",
  "getting": "get",
  "gets": "get",
  "got": "get",
  "coming": "come",
  "comes": "come",
  "came": "come",
  "seeing": "see",
  "sees": "see",
  "saw": "see",
  "seen": "see",
  "knowing": "know",
  "knows": "know",
  "knew": "know",
  "known": "know",
  "thinking": "think",
  "thinks": "think",
  "thought": "think",
  "wanting": "want",
  "wants": "want",
  "wanted": "want",
  "finding": "find",
  "finds": "find",
  "found": "find",
  "telling": "tell",
  "tells": "tell",
  "told": "tell",
  "asking": "ask",
  "asks": "ask",
  "asked": "ask",
  "working": "work",
  "works": "work",
  "feeling": "feel",
  "feels": "feel",
  "felt": "feel",
  "trying": "try",
  "tries": "try",
  "leaving": "leave",
  "leaves": "leave",
  "left": "leave",
  "calling": "call",
  "calls": "call",
  "called": "call",
  "keeping": "keep",
  "keeps": "keep",
  "kept": "keep",
  "beginning": "begin",
  "begins": "begin",
  "began": "begin",
  "begun": "begin",
  "showing": "show",
  "shows": "show",
  "showed": "show",
  "shown": "show",
  "hearing": "hear",
  "hears": "hear",
  "heard": "hear",
  "playing": "play",
  "plays": "play",
  "played": "play",
  "living": "live",
  "lives": "live",
  "loved": "love",
  "loving": "love",
  "loves": "love",
  "believing": "believe",
  "believes": "believe",
  "believed": "believe",
  "bringing": "bring",
  "brings": "bring",
  "brought": "bring",
  "happening": "happen",
  "happens": "happen",
  "happened": "happen",
  "writing": "write",
  "writes": "write",
  "wrote": "write",
  "written": "write",
  "standing": "stand",
  "stands": "stand",
  "stood": "stand",
  "losing": "lose",
  "loses": "lose",
  "lost": "lose",
  "paying": "pay",
  "pays": "pay",
  "paid": "pay",
  "meeting": "meet",
  "meets": "meet",
  "met": "meet",
  "included": "include",
  "including": "include",
  "includes": "include",
  "continuing": "continue",
  "continues": "continue",
  "continued": "continue",
  "setting": "set",
  "sets": "set",
  "learning": "learn",
  "learns": "learn",
  "learned": "learn",
  "changing": "change",
  "changes": "change",
  "changed": "change",
  "leading": "lead",
  "leads": "lead",
  "led": "lead",
  "understanding": "understand",
  "understands": "understand",
  "watching": "watch",
  "watches": "watch",
  "watched": "watch",
  "following": "follow",
  "follows": "follow",
  "stopping": "stop",
  "stops": "stop",
  "stopped": "stop",
  "speaking": "speak",
  "speaks": "speak",
  "spoke": "speak",
  "spoken": "speak",
  "reading": "read",
  "reads": "read",
  "allowing": "allow",
  "allows": "allow",
  "allowed": "allow",
  "adding": "add",
  "adds": "add",
  "added": "add",
  "spending": "spend",
  "spends": "spend",
  "spent": "spend",
  "growing": "grow",
  "grows": "grow",
  "grew": "grow",
  "grown": "grow",
  "opening": "open",
  "opens": "open",
  "opened": "open",
  "winning": "win",
  "wins": "win",
  "won": "win",
  "offering": "offer",
  "offers": "offer",
  "offered": "offer",
  "remembering": "remember",
  "remembers": "remember",
  "remembered": "remember",
  "considering": "consider",
  "considers": "consider",
  "considered": "consider",
  "appearing": "appear",
  "appears": "appear",
  "appeared": "appear",
  "buying": "buy",
  "buys": "buy",
  "bought": "buy",
  "waiting": "wait",
  "waits": "wait",
  "waited": "wait",
  "serving": "serve",
  "serves": "serve",
  "served": "serve",
  "dying": "die",
  "dies": "die",
  "died": "die",
  "sending": "send",
  "sends": "send",
  "sent": "send",
  "expecting": "expect",
  "expects": "expect",
  "expected": "expect",
  "building": "build",
  "builds": "build",
  "staying": "stay",
  "stays": "stay",
  "stayed": "stay",
  "falling": "fall",
  "falls": "fall",
  "fell": "fall",
  "fallen": "fall",
  "cutting": "cut",
  "cuts": "cut",
  "reaching": "reach",
  "reaches": "reach",
  "reached": "reach",
  "killing": "kill",
  "kills": "kill",
  "killed": "kill",
  "remaining": "remain",
  "remains": "remain",
  "remained": "remain",
  "suggesting": "suggest",
  "suggests": "suggest",
  "suggested": "suggest",
  "raising": "raise",
  "raises": "raise",
  "raised": "raise",
  "passing": "pass",
  "passes": "pass",
  "passed": "pass",
  "selling": "sell",
  "sells": "sell",
  "sold": "sell",
  "requiring": "require",
  "requires": "require",
  "required": "require",
  "reporting": "report",
  "reports": "report",
  "reported": "report",
  "deciding": "decide",
  "decides": "decide",
  "decided": "decide",
  "pulling": "pull",
  "pulls": "pull",
  "pulled": "pull",
  "developing": "develop",
  "develops": "develop",
  "developed": "develop",
  "studying": "study",
  "studies": "study",
  "studied": "study",
  "explaining": "explain",
  "explains": "explain",
  "explained": "explain",
  "producing": "produce",
  "produces": "produce",
  "produced": "produce",
  "driving": "drive",
  "drives": "drive",
  "flying": "fly",
  "flies": "fly",
  "flew": "fly",
  "flown": "fly",
  "eating": "eat",
  "eats": "eat",
  "ate": "eat",
  "eaten": "eat",
  "drinking": "drink",
  "drinks": "drink",
  "drank": "drink",
  "drunk": "drink",
  "sleeping": "sleep",
  "sleeps": "sleep",
  "slept": "sleep",
  "teaching": "teach",
  "teaches": "teach",
  "taught": "teach",
  "fighting": "fight",
  "fights": "fight",
  "fought": "fight",
  "rising": "rise",
  "rises": "rise",
  "rose": "rise",
  "risen": "rise",
  "dreaming": "dream",
  "dreams": "dream",
  "choosing": "choose",
  "chooses": "choose",
  "chose": "choose",
  "chosen": "choose",
  "holding": "hold",
  "holds": "hold",
  "held": "hold",
  "throwing": "throw",
  "throws": "throw",
  "threw": "throw",
  "thrown": "throw",
  "catching": "catch",
  "catches": "catch",
  "caught": "catch",
  "hitting": "hit",
  "drawing": "draw",
  "dealing": "deal",
  "deals": "deal",
  "dealt": "deal",
  "meaning": "mean",
  "meant": "mean",
  "wearing": "wear",
  "wears": "wear",
  "wore": "wear",
  "worn": "wear",
  "breaking": "break",
  "breaks": "break",
  "broke": "break",
  "broken": "break",
  "hanging": "hang",
  "rides": "ride",
  "riding": "ride",
  "rode": "ride",
  "ridden": "ride",
  "singing": "sing",
  "sings": "sing",
  "sang": "sing",
  "sung": "sing",
  "shouting": "shout",
  "shouts": "shout",
  "shouted": "shout",
  "closing": "close",
  "closes": "close",
  "closed": "close",
  "signing": "sign",
  "signs": "sign",
  "signed": "sign",
  "listening": "listen",
  "listens": "listen",
  "listened": "listen",
  "picking": "pick",
  "picks": "pick",
  "picked": "pick",
  "planning": "plan",
  "plans": "plan",
  "pointing": "point",
  "points": "point",
  "pointed": "point",
  "presenting": "present",
  "presents": "present",
  "presented": "present",
  "putting": "put",
  "puts": "put",
  "hurting": "hurt",
  "hurts": "hurt",
  "hurting": "hurt",
  "starting": "start",
  "starts": "start",
  "started": "start",
  "sharing": "share",
  "shares": "share",
  "shared": "share",
  "saving": "save",
  "saves": "save",
  "saved": "save",
  "selecting": "select",
  "selects": "select",
  "selected": "select",
  "lying": "lie",
  "lays": "lay",
  "laid": "lay",
  "finishing": "finish",
  "finishes": "finish",
  "finished": "finish",
  "enjoying": "enjoy",
  "enjoys": "enjoy",
  "enjoyed": "enjoy",
  "realizing": "realize",
  "realizes": "realize",
  "realized": "realize",
  "happening": "happen",
  "happens": "happen",
  "happened": "happen",
  "believing": "believe",
  "believes": "believe",
  "believed": "believe",
  "receiving": "receive",
  "receives": "receive",
  "received": "receive",
  "creating": "create",
  "creates": "create",
  "created": "create",
  "carrying": "carry",
  "carries": "carry",
  "carried": "carry",
  "breaking": "break",
  "breaks": "break",
  "broke": "break",
  "broken": "break",
  "driving": "drive",
  "drives": "drive",
  "drove": "drive",
  "driven": "drive",
  "dying": "die",
  "dies": "die",
  "died": "die",
  "moving": "move",
  "moves": "move",
  "moved": "move",
  "having": "have",
  "has": "have",
  "had": "have",
  "talking": "talk",
  "talks": "talk",
  "talked": "talk",
  "saying": "say",
  "says": "say",
  "said": "say",
  "supposing": "suppose",
  "supposes": "suppose",
  "supposed": "suppose",
  "watching": "watch",
  "watches": "watch",
  "watched": "watch",
  "using": "use",
  "uses": "use",
  "used": "use",
  "trying": "try",
  "tries": "try",
  "tried": "try",
  "touching": "touch",
  "touches": "touch",
  "touched": "touch",
  "handing": "hand",
  "hands": "hand",
  "handed": "hand",
  "looking": "look",
  "looks": "look",
  "looked": "look",
  "turning": "turn",
  "turns": "turn",
  "turned": "turn",
  "working": "work",
  "works": "work",
  "worked": "work",
  "wanting": "want",
  "wants": "want",
  "wanted": "want",
  "needing": "need",
  "needs": "need",
  "needed": "need",
  "helping": "help",
  "helps": "help",
  "helped": "help",
  "showing": "show",
  "shows": "show",
  "showed": "show",
  "shown": "show",
  "feeding": "feed",
  "feeds": "feed",
  "fed": "feed",
  "seeming": "seem",
  "seems": "seem",
  "seemed": "seem",
  "forming": "form",
  "forms": "form",
  "formed": "form",
  "handling": "handle",
  "handles": "handle",
  "handled": "handle",
  "playing": "play",
  "plays": "play",
  "played": "play",
  "affecting": "affect",
  "affects": "affect",
  "affected": "affect",
  "containing": "contain",
  "contains": "contain",
  "containing": "contain",
  "holding": "hold",
  "holds": "hold",
  "held": "hold",
  "covering": "cover",
  "covers": "cover",
  "covered": "cover",
  "bringing": "bring",
  "brings": "bring",
  "brought": "bring",
  "adding": "add",
  "adds": "add",
  "added": "add",
  "maintaining": "maintain",
  "maintains": "maintain",
  "maintained": "maintain",
  "relating": "relate",
  "relates": "relate",
  "related": "relate",
  "depending": "depend",
  "depends": "depend",
  "depending": "depend",
  "discovering": "discover",
  "discovers": "discover",
  "discovered": "discover",
  "answering": "answer",
  "answers": "answer",
  "answered": "answer",
  "recognizing": "recognize",
  "recognizes": "recognize",
  "recognized": "recognize",
  "treating": "treat",
  "treats": "treat",
  "treated": "treat",
  "asking": "ask",
  "asks": "ask",
  "asked": "ask",
  "serving": "serve",
  "serves": "serve",
  "served": "serve",
  "sitting": "sit",
  "sits": "sit",
  "sat": "sit",
  "running": "run",
  "runs": "run",
  "ran": "run",
  "moving": "move",
  "moves": "move",
  "moved": "move",
  "living": "live",
  "lives": "live",
  "lived": "live",
  "believing": "believe",
  "believes": "believe",
  "believed": "believe",
  "describing": "describe",
  "describes": "describe",
  "described": "describe",
  "performing": "perform",
  "performs": "perform",
  "performed": "perform",
  "developing": "develop",
  "develops": "develop",
  "developed": "develop",
  "producing": "produce",
  "produces": "produce",
  "produced": "produce",
  "indicating": "indicate",
  "indicates": "indicate",
  "indicated": "indicate",
  "supplying": "supply",
  "supplies": "supply",
  "supplied": "supply",
  "enabling": "enable",
  "enables": "enable",
  "enabled": "enable",
  "offering": "offer",
  "offers": "offer",
  "offered": "offer",
  "utilizing": "utilize",
  "utilizes": "utilize",
  "viewing": "view",
  "views": "view",
  "viewed": "view",
  "visiting": "visit",
  "visits": "visit",
  "visited": "visit",
  "voting": "vote",
  "votes": "vote",
  "voted": "vote",
  "waking": "wake",
  "wakes": "wake",
  "woke": "wake",
  "woken": "wake",
  "wandering": "wander",
  "wanders": "wander",
  "wandered": "wander",
  "warning": "warn",
  "warns": "warn",
  "warned": "warn",
  "washing": "wash",
  "washes": "wash",
  "washed": "wash",
  "wasting": "waste",
  "wastes": "waste",
  "wasted": "waste",
  "waving": "wave",
  "waves": "wave",
  "waved": "wave",
  "weighing": "weigh",
  "weighs": "weigh",
  "welcoming": "welcome",
  "welcomes": "welcome",
  "welcomed": "welcome",
  "wishing": "wish",
  "wishes": "wish",
  "wished": "wish",
  "withdrawing": "withdraw",
  "withdraws": "withdraw",
  "withdrew": "withdraw",
  "withdrawn": "withdraw",
  "witnessing": "witness",
  "witnesses": "witness",
  "wondering": "wonder",
  "wonders": "wonder",
  "wondered": "wonder",
  "worrying": "worry",
  "worries": "worry",
  "worried": "worry",
  "wrapping": "wrap",
  "wraps": "wrap",
  "wrapped": "wrap",
  "improving": "improve",
  "improves": "improve",
  "improved": "improve",
  "increasing": "increase",
  "increases": "increase",
  "increased": "increase",
  "arguing": "argue",
  "argues": "argue",
  "argued": "argue",
  "comparing": "compare",
  "compares": "compare",
  "compared": "compare",
  "connecting": "connect",
  "connects": "connect",
  "connected": "connect",
  "protected": "protect",
  "protecting": "protect",
  "protects": "protect",
  "hurrying": "hurry",
  "hurries": "hurry",
  "hurried": "hurry",
  "injuring": "injure",
  "injures": "injure",
  "injured": "injure",
  "introducing": "introduce",
  "introduces": "introduce",
  "introduced": "introduce",
  "inviting": "invite",
  "invites": "invite",
  "invited": "invite",
  "jumping": "jump",
  "jumps": "jump",
  "jumped": "jump",
  "laughing": "laugh",
  "laughs": "laugh",
  "laughed": "laugh",
  "laying": "lay",
  "lays": "lay",
  "laid": "lay",
};

/**
 * 词形还原 - 将英文单词还原为其词根形式
 */
function lemmatize(word: string): string {
  const lowerWord = word.toLowerCase();

  // 1. 首先检查不规则动词表
  if (irregularVerbs[lowerWord]) {
    return irregularVerbs[lowerWord];
  }

  // 2. 检查常见动词形式表
  if (verbForms[lowerWord]) {
    return verbForms[lowerWord];
  }

  // 3. 检查不规则名词
  if (irregularNouns[lowerWord]) {
    return irregularNouns[lowerWord];
  }

  // 4. 应用后缀规则
  for (const rule of suffixRules) {
    if (lowerWord.endsWith(rule.suffix)) {
      const base = lowerWord.slice(0, -rule.remove);
      const result = rule.add ? base + rule.add : base;
      // 确保还原后的单词至少有两个字母
      if (result.length >= 2) {
        return result;
      }
    }
  }

  // 5. 返回原单词（小写）
  return lowerWord;
}

/**
 * Process text into structured segments with lemmas
 * Handles EPUB heading markers like [H2]Chapter 1[/H2]
 */
function processTextToSegments(text: string | undefined | null): ProcessedContent {
  if (!text) return [];

  // Split by double newlines to get raw paragraphs
  const rawParagraphs = text.split(/\n\n+/).filter(p => p.trim());
  const result: ProcessedParagraph[] = [];

  for (const rawParagraph of rawParagraphs) {
    const trimmed = rawParagraph.trim();
    if (!trimmed) continue;

    // Check if this is a heading marker [H1]...[/H1] to [H6]...[/H6]
    const headingMatch = trimmed.match(/^\[H(\d)\]([\s\S]*?)\[\/H\d\]$/);

    if (headingMatch) {
      const level = parseInt(headingMatch[1], 10);
      const headingText = headingMatch[2].trim();

      if (headingText) {
        // Process heading text with tokenization (so words in headings can be clicked)
        const segments: ProcessedSegment[] = [];
        const regex = /([a-zA-Z]+|[^a-zA-Z\s]+|\s+)/g;
        let segMatch;

        while ((segMatch = regex.exec(headingText)) !== null) {
          const token = segMatch[0];
          if (/^\s+$/.test(token)) {
            segments.push({ text: token, lemma: "", type: "space" });
          } else if (/^[a-zA-Z]+$/.test(token)) {
            segments.push({ text: token, lemma: lemmatize(token.toLowerCase()), type: "word" });
          } else {
            segments.push({ text: token, lemma: "", type: "punctuation" });
          }
        }

        result.push({ segments, headingLevel: level });
      }
    } else {
      // Regular paragraph
      const segments: ProcessedSegment[] = [];
      const regex = /([a-zA-Z]+|[^a-zA-Z\s]+|\s+)/g;
      let segMatch;

      while ((segMatch = regex.exec(trimmed)) !== null) {
        const token = segMatch[0];
        if (/^\s+$/.test(token)) {
          segments.push({ text: token, lemma: "", type: "space" });
        } else if (/^[a-zA-Z]+$/.test(token)) {
          segments.push({ text: token, lemma: lemmatize(token.toLowerCase()), type: "word" });
        } else {
          segments.push({ text: token, lemma: "", type: "punctuation" });
        }
      }

      result.push({ segments });
    }
  }

  return result;
}

// Worker message handler
self.onmessage = function(e: MessageEvent<{ text: string }>) {
  const { text } = e.data;
  const result = processTextToSegments(text);
  self.postMessage({ result });
};
